// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZn1eoch8lvH_dKFgTD90FkxF_AkNfJpM',
    appId: '1:921758905393:web:01ac287414aa593cd25110',
    messagingSenderId: '921758905393',
    projectId: 'rathtech-a73db',
    authDomain: 'rathtech-a73db.firebaseapp.com',
    storageBucket: 'rathtech-a73db.firebasestorage.app',
    measurementId: 'G-SMR2W9LFP4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASJlmp4jZDMtSNQLgVmJZS8rxsIQd_1ug',
    appId: '1:921758905393:android:a29b7e3b2d05f96cd25110',
    messagingSenderId: '921758905393',
    projectId: 'rathtech-a73db',
    storageBucket: 'rathtech-a73db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBioTkZJMi965bGEVH0VdsfvV3Mvw-44mE',
    appId: '1:921758905393:ios:e8a8d78fd62f1342d25110',
    messagingSenderId: '921758905393',
    projectId: 'rathtech-a73db',
    storageBucket: 'rathtech-a73db.firebasestorage.app',
    iosBundleId: 'com.example.userPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBioTkZJMi965bGEVH0VdsfvV3Mvw-44mE',
    appId: '1:921758905393:ios:e8a8d78fd62f1342d25110',
    messagingSenderId: '921758905393',
    projectId: 'rathtech-a73db',
    storageBucket: 'rathtech-a73db.firebasestorage.app',
    iosBundleId: 'com.example.userPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZn1eoch8lvH_dKFgTD90FkxF_AkNfJpM',
    appId: '1:921758905393:web:01ac287414aa593cd25110',
    messagingSenderId: '921758905393',
    projectId: 'rathtech-a73db',
    authDomain: 'rathtech-a73db.firebaseapp.com',
    storageBucket: 'rathtech-a73db.firebasestorage.app',
    measurementId: 'G-SMR2W9LFP4',
  );
}
